name: Release Java Jar

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn clean package

      - name: Rename JAR
        run: |
          mkdir release
          cp target/*.jar release/app.jar

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Upload JAR to Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/app.jar
          token: ${{ secrets.PERSONAL_TOKEN }}
